# Generated by Django 6.1.1 on 2026-09-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('tamanho', models.CharField(max_length=10)),
                ('cor', models.CharField(max_length=30)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
