# Generated by Django 6.1.1 on 2026-09-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_produto_categoria_produto_cor_produto_tamanho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
