# Generated by Django 6.1.1 on 2026-10-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_produto_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="genero",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
            ),
        ),
    ]
