# Generated by Django 6.1.1 on 2026-10-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_produto_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Foto (enviar arquivo)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imagem (link)'),
        ),
    ]
